org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-logistics-networks
addon_name=BlueMap Logistics Networks Add-on
addon_version=0.1.0-alpha.2
addon_group=io.github.jan-guenter
artifact_id=bluemap-logistics-networks-addon
bluemap_version=5.22-feature.backport-5.23-stateless-java-web-server-46
accepted_jar_size=67367
accepted_jar_sha256=5f813504e2dccd63ad0a2cc1bd33a129da2e2934e5576d149b6b215c12ba8f18
accepted_sources_jar_size=31656
accepted_sources_jar_sha256=df0b53155df3c1add4fbea839fbc125a212ed2c6a4d25ebe812c4801a85bfa98
accepted_pom_size=1408
accepted_pom_sha256=d2d0f5443803bd3e6be9fb874a3a4e7997f14c6b88dd82fb24359f4b9e15730b
accepted_module_size=2894
accepted_module_sha256=941a1cef0811d1f88d974f7c401141aa5d73ce8e56a04a13b7a35a5c4a341936
