# Generated by gallery/generate.py; do not edit.
scoreboard objectives add ln_gallery dummy
scoreboard players add #builds ln_gallery 0
execute if score #builds ln_gallery matches 1.. run tellraw @a [{"text":"LogisticsNetworks gallery already built; guard retained it."}]
execute if score #builds ln_gallery matches 0 run function logisticsnetworks_gallery:build_once
