# Generated by gallery/generate.py; do not edit.
scoreboard players add #builds ln_gallery 1
forceload add 160 160 191 191
function logisticsnetworks_gallery:clear
fill 160 99 160 191 99 191 minecraft:smooth_stone
# A1: stock computer north; stock control
setblock 164 100 164 logisticsnetworks:computer[facing=north]
# A2: stock computer east; stock control
setblock 170 100 164 logisticsnetworks:computer[facing=east]
# A3: stock computer south; stock control
setblock 176 100 164 logisticsnetworks:computer[facing=south]
# A4: stock computer west; stock control
setblock 182 100 164 logisticsnetworks:computer[facing=west]
# B1: visible isolated; synthetic prototype only
setblock 164 100 171 minecraft:stone
summon logisticsnetworks:logistics_node 164.5 100.5 171.5 {UUID:[I;940189615,927423789,-1866110367,-273990117],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_b1"],AttachedPos:45079977439332L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# B2: hidden zero-geometry control; synthetic prototype only
setblock 170 100 171 minecraft:stone
summon logisticsnetworks:logistics_node 170.5 100.5 171.5 {UUID:[I;880387081,-2128849759,-1567394761,1255260855],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_b2"],AttachedPos:46729244880996L,Valid:1b,RenderVisible:0b,Highlighted:0b}
# C1: straight west; synthetic prototype only
setblock 176 100 171 minecraft:stone
summon logisticsnetworks:logistics_node 176.5 100.5 171.5 {UUID:[I;-1935001563,1819956591,-1895817105,-1576981713],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_c1"],AttachedPos:48378512322660L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# C2: straight east; synthetic prototype only
setblock 177 100 171 minecraft:stone
summon logisticsnetworks:logistics_node 177.5 100.5 171.5 {UUID:[I;1746044569,283597917,-1164672795,616194317],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_c2"],AttachedPos:48653390229604L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# D1: L corner; synthetic prototype only
setblock 164 100 179 minecraft:stone
summon logisticsnetworks:logistics_node 164.5 100.5 179.5 {UUID:[I;53167864,-1554623905,-1437812590,877283270],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_d1"],AttachedPos:45079977472100L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# D2: L east arm; synthetic prototype only
setblock 165 100 179 minecraft:stone
summon logisticsnetworks:logistics_node 165.5 100.5 179.5 {UUID:[I;-1228033340,1307661351,-1531428355,1011258033],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_d2"],AttachedPos:45354855379044L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# D3: L south arm; synthetic prototype only
setblock 164 100 180 minecraft:stone
summon logisticsnetworks:logistics_node 164.5 100.5 180.5 {UUID:[I;-1127666320,1193499728,-1776004264,1581393308],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_d3"],AttachedPos:45079977476196L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# E1: square north-west; synthetic prototype only
setblock 176 100 179 minecraft:stone
summon logisticsnetworks:logistics_node 176.5 100.5 179.5 {UUID:[I;1990655488,-729065006,-1453263725,-2142859619],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_e1"],AttachedPos:48378512355428L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# E2: square north-east; synthetic prototype only
setblock 177 100 179 minecraft:stone
summon logisticsnetworks:logistics_node 177.5 100.5 179.5 {UUID:[I;-2139256889,-1104129017,-1167971484,1341427386],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_e2"],AttachedPos:48653390262372L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# E3: square south-west; synthetic prototype only
setblock 176 100 180 minecraft:stone
summon logisticsnetworks:logistics_node 176.5 100.5 180.5 {UUID:[I;-1890216443,-154774001,-1100635453,-1733210730],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_e3"],AttachedPos:48378512359524L,Valid:1b,RenderVisible:1b,Highlighted:0b}
# E4: square south-east; synthetic prototype only
setblock 177 100 180 minecraft:stone
summon logisticsnetworks:logistics_node 177.5 100.5 180.5 {UUID:[I;908184392,1556500490,-1585640939,-74329550],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],Tags:["ln_gallery","ln_e4"],AttachedPos:48653390266468L,Valid:1b,RenderVisible:1b,Highlighted:0b}
function logisticsnetworks_gallery:verify_immediate
schedule function logisticsnetworks_gallery:verify_20t 20t replace
schedule function logisticsnetworks_gallery:verify_100t 100t replace
