# Generated by gallery/generate.py; do not edit.
execute if score #build_pending ln_gallery matches 1 if score #builds ln_gallery matches 0 if score #clear_pending ln_gallery matches 0 run function logisticsnetworks_gallery:build_loaded
