# Generated by gallery/generate.py; do not edit.
execute if score #builds ln_gallery matches 1.. run tellraw @a [{"text":"LogisticsNetworks gallery already built; guard retained it."}]
execute if score #build_pending ln_gallery matches 1 if score #builds ln_gallery matches 0 run tellraw @a [{"text":"LogisticsNetworks gallery lifecycle already pending."}]
execute if score #clear_pending ln_gallery matches 1 run tellraw @a [{"text":"LogisticsNetworks gallery lifecycle already pending."}]
execute if score #verification_pending ln_gallery matches 1 if score #builds ln_gallery matches 0 run tellraw @a [{"text":"LogisticsNetworks gallery lifecycle already pending."}]
execute if score #builds ln_gallery matches 0 if score #build_pending ln_gallery matches 0 if score #clear_pending ln_gallery matches 0 if score #verification_pending ln_gallery matches 0 run function logisticsnetworks_gallery:prepare_build
