# Generated by gallery/generate.py; do not edit.
schedule clear logisticsnetworks_gallery:verify_20t
schedule clear logisticsnetworks_gallery:verify_100t
kill @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31]
fill 160 99 160 191 108 191 minecraft:air
