# Generated by gallery/generate.py; do not edit.
# PROTOTYPE ONLY: destructively targets every loaded LogisticsNetworks node dimension-wide.
schedule clear logisticsnetworks_gallery:verify_20t
schedule clear logisticsnetworks_gallery:verify_100t
logisticsnetworks removeNodes
fill 160 99 160 191 108 191 minecraft:air
