# Generated by gallery/generate.py; do not edit.
function logisticsnetworks_gallery:loaded_cleanup
scoreboard players set #builds ln_gallery 0
scoreboard players set #build_pending ln_gallery 0
scoreboard players set #verification_pending ln_gallery 0
scoreboard players set #clear_pending ln_gallery 0
forceload remove 160 160 191 191
scoreboard players set #ticket_held ln_gallery 0
