# Generated by gallery/generate.py; do not edit.
# PROTOTYPE ONLY: destructively targets every loaded LogisticsNetworks node dimension-wide.
logisticsnetworks removeNodes
fill 160 99 160 191 108 191 minecraft:air
