# Generated by gallery/generate.py; do not edit.
scoreboard objectives add ln_gallery dummy
scoreboard players add #builds ln_gallery 0
scoreboard players add #build_pending ln_gallery 0
scoreboard players add #clear_pending ln_gallery 0
scoreboard players add #verification_pending ln_gallery 0
scoreboard players add #ticket_held ln_gallery 0
