# Generated by gallery/generate.py; do not edit.
schedule clear logisticsnetworks_gallery:build_once
schedule clear logisticsnetworks_gallery:verify_20t
schedule clear logisticsnetworks_gallery:verify_100t
scoreboard players set #build_pending ln_gallery 0
scoreboard players set #verification_pending ln_gallery 0
scoreboard players set #clear_pending ln_gallery 1
forceload add 160 160 191 191
scoreboard players set #ticket_held ln_gallery 1
schedule function logisticsnetworks_gallery:clear_once 20t replace
