# Generated by gallery/generate.py; do not edit.
scoreboard players set #build_pending ln_gallery 1
forceload add 160 160 191 191
scoreboard players set #ticket_held ln_gallery 1
schedule function logisticsnetworks_gallery:build_once 20t replace
