# Generated by gallery/generate.py; do not edit.
function logisticsnetworks_gallery:verify
scoreboard players operation #immediate_failures ln_gallery = #failures ln_gallery
scoreboard players operation #immediate_checked ln_gallery = #checked ln_gallery
tellraw @a [{"text":"LogisticsNetworks gallery immediate: "},{"score":{"name":"#immediate_checked","objective":"ln_gallery"}},{"text":" checks, "},{"score":{"name":"#immediate_failures","objective":"ln_gallery"}},{"text":" failures"}]
