# Generated by gallery/generate.py; do not edit.
scoreboard players set #failures ln_gallery 0
scoreboard players set #checked ln_gallery 0
execute unless score #builds ln_gallery matches 1 run say LN_GALLERY_FAIL:build_count_exact_1
execute unless score #builds ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 164 100 164 logisticsnetworks:computer[facing=north] run say LN_GALLERY_FAIL:computer_A1_exact_state
execute unless block 164 100 164 logisticsnetworks:computer[facing=north] run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 170 100 164 logisticsnetworks:computer[facing=east] run say LN_GALLERY_FAIL:computer_A2_exact_state
execute unless block 170 100 164 logisticsnetworks:computer[facing=east] run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 176 100 164 logisticsnetworks:computer[facing=south] run say LN_GALLERY_FAIL:computer_A3_exact_state
execute unless block 176 100 164 logisticsnetworks:computer[facing=south] run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 182 100 164 logisticsnetworks:computer[facing=west] run say LN_GALLERY_FAIL:computer_A4_exact_state
execute unless block 182 100 164 logisticsnetworks:computer[facing=west] run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 164 100 171 minecraft:stone run say LN_GALLERY_FAIL:host_B1_stone
execute unless block 164 100 171 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 170 100 171 minecraft:stone run say LN_GALLERY_FAIL:host_B2_stone
execute unless block 170 100 171 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 176 100 171 minecraft:stone run say LN_GALLERY_FAIL:host_C1_stone
execute unless block 176 100 171 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 177 100 171 minecraft:stone run say LN_GALLERY_FAIL:host_C2_stone
execute unless block 177 100 171 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 164 100 179 minecraft:stone run say LN_GALLERY_FAIL:host_D1_stone
execute unless block 164 100 179 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 165 100 179 minecraft:stone run say LN_GALLERY_FAIL:host_D2_stone
execute unless block 165 100 179 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 164 100 180 minecraft:stone run say LN_GALLERY_FAIL:host_D3_stone
execute unless block 164 100 180 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 176 100 179 minecraft:stone run say LN_GALLERY_FAIL:host_E1_stone
execute unless block 176 100 179 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 177 100 179 minecraft:stone run say LN_GALLERY_FAIL:host_E2_stone
execute unless block 177 100 179 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 176 100 180 minecraft:stone run say LN_GALLERY_FAIL:host_E3_stone
execute unless block 176 100 180 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless block 177 100 180 minecraft:stone run say LN_GALLERY_FAIL:host_E4_stone
execute unless block 177 100 180 minecraft:stone run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31]
execute unless score #observed ln_gallery matches 11 run say LN_GALLERY_FAIL:node_envelope_count_11
execute unless score #observed ln_gallery matches 11 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# B1: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_B1_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] {UUID:[I;940189615,927423789,-1866110367,-273990117],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45079977439332L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[164.5d,100.5d,171.5d]} run say LN_GALLERY_FAIL:node_B1_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] {UUID:[I;940189615,927423789,-1866110367,-273990117],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45079977439332L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[164.5d,100.5d,171.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_B1_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_B1_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_B1_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_B1_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_B1_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b1,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# B2: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_B2_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] {UUID:[I;880387081,-2128849759,-1567394761,1255260855],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:46729244880996L,Valid:1b,RenderVisible:0b,Highlighted:0b,Pos:[170.5d,100.5d,171.5d]} run say LN_GALLERY_FAIL:node_B2_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] {UUID:[I;880387081,-2128849759,-1567394761,1255260855],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:46729244880996L,Valid:1b,RenderVisible:0b,Highlighted:0b,Pos:[170.5d,100.5d,171.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_B2_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_B2_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_B2_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_B2_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_B2_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_b2,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# C1: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_C1_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] {UUID:[I;-1935001563,1819956591,-1895817105,-1576981713],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48378512322660L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[176.5d,100.5d,171.5d]} run say LN_GALLERY_FAIL:node_C1_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] {UUID:[I;-1935001563,1819956591,-1895817105,-1576981713],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48378512322660L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[176.5d,100.5d,171.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_C1_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_C1_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_C1_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_C1_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_C1_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c1,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# C2: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_C2_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] {UUID:[I;1746044569,283597917,-1164672795,616194317],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48653390229604L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[177.5d,100.5d,171.5d]} run say LN_GALLERY_FAIL:node_C2_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] {UUID:[I;1746044569,283597917,-1164672795,616194317],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48653390229604L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[177.5d,100.5d,171.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_C2_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_C2_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_C2_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_C2_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_C2_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_c2,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# D1: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_D1_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] {UUID:[I;53167864,-1554623905,-1437812590,877283270],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45079977472100L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[164.5d,100.5d,179.5d]} run say LN_GALLERY_FAIL:node_D1_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] {UUID:[I;53167864,-1554623905,-1437812590,877283270],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45079977472100L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[164.5d,100.5d,179.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_D1_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_D1_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_D1_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_D1_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_D1_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d1,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# D2: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_D2_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] {UUID:[I;-1228033340,1307661351,-1531428355,1011258033],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45354855379044L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[165.5d,100.5d,179.5d]} run say LN_GALLERY_FAIL:node_D2_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] {UUID:[I;-1228033340,1307661351,-1531428355,1011258033],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45354855379044L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[165.5d,100.5d,179.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_D2_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_D2_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_D2_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_D2_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_D2_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d2,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# D3: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_D3_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] {UUID:[I;-1127666320,1193499728,-1776004264,1581393308],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45079977476196L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[164.5d,100.5d,180.5d]} run say LN_GALLERY_FAIL:node_D3_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] {UUID:[I;-1127666320,1193499728,-1776004264,1581393308],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:45079977476196L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[164.5d,100.5d,180.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_D3_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_D3_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_D3_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_D3_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_D3_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_d3,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# E1: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_E1_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] {UUID:[I;1990655488,-729065006,-1453263725,-2142859619],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48378512355428L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[176.5d,100.5d,179.5d]} run say LN_GALLERY_FAIL:node_E1_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] {UUID:[I;1990655488,-729065006,-1453263725,-2142859619],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48378512355428L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[176.5d,100.5d,179.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_E1_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_E1_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_E1_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_E1_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_E1_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e1,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# E2: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_E2_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] {UUID:[I;-2139256889,-1104129017,-1167971484,1341427386],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48653390262372L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[177.5d,100.5d,179.5d]} run say LN_GALLERY_FAIL:node_E2_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] {UUID:[I;-2139256889,-1104129017,-1167971484,1341427386],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48653390262372L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[177.5d,100.5d,179.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_E2_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_E2_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_E2_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_E2_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_E2_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e2,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# E3: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_E3_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] {UUID:[I;-1890216443,-154774001,-1100635453,-1733210730],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48378512359524L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[176.5d,100.5d,180.5d]} run say LN_GALLERY_FAIL:node_E3_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] {UUID:[I;-1890216443,-154774001,-1100635453,-1733210730],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48378512359524L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[176.5d,100.5d,180.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_E3_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_E3_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_E3_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_E3_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_E3_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e3,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
# E4: exact live synthetic entity checks
execute store result score #observed ln_gallery run execute if entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4]
execute unless score #observed ln_gallery matches 1 run say LN_GALLERY_FAIL:node_E4_tag_count_1
execute unless score #observed ln_gallery matches 1 run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] {UUID:[I;908184392,1556500490,-1585640939,-74329550],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48653390266468L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[177.5d,100.5d,180.5d]} run say LN_GALLERY_FAIL:node_E4_identity_state_nbt
execute unless data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] {UUID:[I;908184392,1556500490,-1585640939,-74329550],Motion:[0.0d,0.0d,0.0d],Rotation:[0.0f,0.0f],AttachedPos:48653390266468L,Valid:1b,RenderVisible:1b,Highlighted:0b,Pos:[177.5d,100.5d,180.5d]} run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] NetworkId run say LN_GALLERY_FAIL:node_E4_absent_NetworkId
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] NetworkId run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] NetworkName run say LN_GALLERY_FAIL:node_E4_absent_NetworkName
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] NetworkName run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] OwnerUUID run say LN_GALLERY_FAIL:node_E4_absent_OwnerUUID
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] OwnerUUID run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] NodeLabel run say LN_GALLERY_FAIL:node_E4_absent_NodeLabel
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] NodeLabel run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] Upgrades run say LN_GALLERY_FAIL:node_E4_absent_Upgrades
execute if data entity @e[type=logisticsnetworks:logistics_node,x=160,y=99,z=160,dx=31,dy=9,dz=31,tag=ln_e4,sort=arbitrary,limit=1] Upgrades run scoreboard players add #failures ln_gallery 1
scoreboard players add #checked ln_gallery 1
