# Generated by gallery/generate.py; do not edit.
function logisticsnetworks_gallery:verify
scoreboard players operation #20t_failures ln_gallery = #failures ln_gallery
scoreboard players operation #20t_checked ln_gallery = #checked ln_gallery
